<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'pos',
  'author' => '',
  'description' => 'Modules created for the POSSCON example application.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'POSSCON',
  'published_date' => '2012-03-23 02:24:09',
  'type' => 'module',
  'version' => 1332469450,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'POSSCON',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'pos_Attendees',
      'class' => 'pos_Attendees',
      'path' => 'modules/pos_Attendees/pos_Attendees.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'pos_Events',
      'class' => 'pos_Events',
      'path' => 'modules/pos_Events/pos_Events.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'pos_Feedback',
      'class' => 'pos_Feedback',
      'path' => 'modules/pos_Feedback/pos_Feedback.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'pos_Sessions',
      'class' => 'pos_Sessions',
      'path' => 'modules/pos_Sessions/pos_Sessions.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'pos_Speakers',
      'class' => 'pos_Speakers',
      'path' => 'modules/pos_Speakers/pos_Speakers.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'pos_SponsorContacts',
      'class' => 'pos_SponsorContacts',
      'path' => 'modules/pos_SponsorContacts/pos_SponsorContacts.php',
      'tab' => false,
    ),
    6 => 
    array (
      'module' => 'pos_Sponsors',
      'class' => 'pos_Sponsors',
      'path' => 'modules/pos_Sponsors/pos_Sponsors.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_attendees_pos_events_pos_Events.php',
      'to_module' => 'pos_Events',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_attendees_pos_events_pos_Attendees.php',
      'to_module' => 'pos_Attendees',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sessions_pos_feedback_pos_Sessions.php',
      'to_module' => 'pos_Sessions',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sessions_pos_events_pos_Events.php',
      'to_module' => 'pos_Events',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sessions_pos_events_pos_Sessions.php',
      'to_module' => 'pos_Sessions',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_speakers_pos_sessions_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_speakers_activities_calls_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sponsorcontacts_activities_calls_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sponsors_pos_sponsorcontacts_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sponsors_activities_calls_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sponsors_pos_events_pos_Events.php',
      'to_module' => 'pos_Events',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/pos_sponsors_pos_events_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_attendees_pos_eventsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sessions_pos_feedbackMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sessions_pos_eventsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_speakers_pos_sessionsMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_speakers_activities_callsMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_speakers_activities_meetingsMetaData.php',
    ),
    6 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_speakers_activities_notesMetaData.php',
    ),
    7 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_speakers_activities_tasksMetaData.php',
    ),
    8 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_speakers_activities_emailsMetaData.php',
    ),
    9 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsorcontacts_activities_callsMetaData.php',
    ),
    10 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsorcontacts_activities_meetingsMetaData.php',
    ),
    11 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsorcontacts_activities_notesMetaData.php',
    ),
    12 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsorcontacts_activities_tasksMetaData.php',
    ),
    13 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsorcontacts_activities_emailsMetaData.php',
    ),
    14 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_pos_sponsorcontactsMetaData.php',
    ),
    15 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_activities_callsMetaData.php',
    ),
    16 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_activities_meetingsMetaData.php',
    ),
    17 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_activities_notesMetaData.php',
    ),
    18 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_activities_tasksMetaData.php',
    ),
    19 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_activities_emailsMetaData.php',
    ),
    20 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/pos_sponsors_pos_eventsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_Attendees',
      'to' => 'modules/pos_Attendees',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_Events',
      'to' => 'modules/pos_Events',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_Feedback',
      'to' => 'modules/pos_Feedback',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_Sessions',
      'to' => 'modules/pos_Sessions',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_Speakers',
      'to' => 'modules/pos_Speakers',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_SponsorContacts',
      'to' => 'modules/pos_SponsorContacts',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/pos_Sponsors',
      'to' => 'modules/pos_Sponsors',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Events.php',
      'to_module' => 'pos_Events',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Attendees.php',
      'to_module' => 'pos_Attendees',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Feedback.php',
      'to_module' => 'pos_Feedback',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sessions.php',
      'to_module' => 'pos_Sessions',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Events.php',
      'to_module' => 'pos_Events',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sessions.php',
      'to_module' => 'pos_Sessions',
      'language' => 'en_us',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sessions.php',
      'to_module' => 'pos_Sessions',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Speakers.php',
      'to_module' => 'pos_Speakers',
      'language' => 'en_us',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Speakers.php',
      'to_module' => 'pos_Speakers',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Speakers.php',
      'to_module' => 'pos_Speakers',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Speakers.php',
      'to_module' => 'pos_Speakers',
      'language' => 'en_us',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Speakers.php',
      'to_module' => 'pos_Speakers',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Speakers.php',
      'to_module' => 'pos_Speakers',
      'language' => 'en_us',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
      'language' => 'en_us',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
      'language' => 'en_us',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/application.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Events.php',
      'to_module' => 'pos_Events',
      'language' => 'en_us',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
      'language' => 'en_us',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_attendees_pos_events_pos_Events.php',
      'to_module' => 'pos_Events',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_attendees_pos_events_pos_Attendees.php',
      'to_module' => 'pos_Attendees',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sessions_pos_feedback_pos_Feedback.php',
      'to_module' => 'pos_Feedback',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sessions_pos_feedback_pos_Sessions.php',
      'to_module' => 'pos_Sessions',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sessions_pos_events_pos_Events.php',
      'to_module' => 'pos_Events',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sessions_pos_events_pos_Sessions.php',
      'to_module' => 'pos_Sessions',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_pos_sessions_pos_Sessions.php',
      'to_module' => 'pos_Sessions',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_pos_sessions_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_calls_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_meetings_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_notes_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_tasks_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_speakers_activities_emails_pos_Speakers.php',
      'to_module' => 'pos_Speakers',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_calls_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_meetings_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_notes_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_tasks_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsorcontacts_activities_emails_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_pos_sponsorcontacts_pos_SponsorContacts.php',
      'to_module' => 'pos_SponsorContacts',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_pos_sponsorcontacts_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_calls_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_meetings_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_notes_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_tasks_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_activities_emails_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_pos_events_pos_Events.php',
      'to_module' => 'pos_Events',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/pos_sponsors_pos_events_pos_Sponsors.php',
      'to_module' => 'pos_Sponsors',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'pos_speakers_activities_calls_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'pos_speakers_activities_meetings_name',
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'pos_speakers_activities_notes_name',
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'pos_speakers_activities_tasks_name',
      ),
    ),
    6 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    7 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'pos_sponsorcontacts_activities_calls_name',
      ),
    ),
    8 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'pos_sponsorcontacts_activities_meetings_name',
      ),
    ),
    9 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'pos_sponsorcontacts_activities_notes_name',
      ),
    ),
    10 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'pos_sponsorcontacts_activities_tasks_name',
      ),
    ),
    11 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    12 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    13 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'pos_sponsors_activities_calls_name',
      ),
    ),
    14 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'pos_sponsors_activities_meetings_name',
      ),
    ),
    15 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'pos_sponsors_activities_notes_name',
      ),
    ),
    16 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'pos_sponsors_activities_tasks_name',
      ),
    ),
    17 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);